# Generated by Django 3.2.23 on 2023-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Text input optional, (max is length 255 characters)', max_length=255, verbose_name='Bio:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(help_text='Text input REQUIRED, (max is length 150 characters)', max_length=150, null=True, verbose_name='First Name:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(help_text='Text input REQUIRED, (max is length 150 characters)', max_length=150, null=True, verbose_name='Last Name:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(help_text='Text input REQUIRED, (max is length 100 characters)', max_length=100, null=True, verbose_name='Username:'),
        ),
    ]
