# Generated by Django 3.2.23 on 2023-12-12 12:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length=255', max_length=255, null=True, verbose_name='Genre:')),
                ('description', models.TextField(blank=True, help_text='format: not required, max_length=255', max_length=255, verbose_name='Description:')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
    ]
