# Generated by Django 3.2.23 on 2023-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Text input required, (max is length 255 characters)', max_length=255, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Text input required, (max is length 255 characters)', max_length=255, null=True, verbose_name='Genre:'),
        ),
    ]
