# Generated by Django 3.2.23 on 2023-12-12 12:59

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length=255', max_length=255, null=True, verbose_name='Game Name:')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('game_company', models.CharField(help_text='format: not required, max_length=255', max_length=255, null=True, verbose_name='Game Company:')),
                ('game_bio', models.TextField(blank=True, help_text='format: not required, max_length=255', max_length=255, verbose_name='Game Bio:')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='genres.genre')),
            ],
        ),
    ]
