# Generated by Django 3.2.23 on 2023-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_bio',
            field=models.TextField(blank=True, help_text='optionl , (max length is 255)', max_length=255, verbose_name='Game Bio:'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_company',
            field=models.CharField(help_text='required, (max length is 255)', max_length=255, null=True, verbose_name='Game Company:'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='required, (max length is 255)', max_length=255, null=True, verbose_name='Game Name:'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, help_text='format:, YYYY-MM-DD', null=True),
        ),
    ]
